[mysql]
user = "2gmaGF7uE9QHnKq.root"
password = "Yu60VkzGkybKxFQB"
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
dbName = "test"
maxIdleConns = 10
maxOpenConns = 100
tls = true


[rmq]
user = "psnbxfjg"
password = "fmCsjm2o0vcVyFywgR6as3WqBwiuATLN"
host = "cougar.rmq.cloudamqp.com"
vhost = "/psnbxfjg"
port = 5672
queue = "fsm"

